# general settings
name: AttentionBasicVSR
model_type: VideoRecurrentModel
scale: 4
num_gpu: 2  # official: 8 GPUs
manual_seed: 0
crop: true

# dataset and data loader settings
datasets:
  train:
    name: REDS
    type: REDSRecurrentDataset
    dataroot_gt: ../../data/REDS/train_sharp
    dataroot_lq: ../../data/REDS/train_sharp_bicubic/X4
    meta_info_file: basicsr/data/meta_info/meta_info_REDS_GT.txt
    val_partition: REDS4  # set to 'official' when use the official validation partition
    test_mode: False
    io_backend:
      type: disk

    num_frame: 15
    gt_size: 256
    interval_list: [1]
    random_reverse: false
    use_hflip: true
    use_rot: true

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 6
    batch_size_per_gpu: 4
    dataset_enlarge_ratio: 200
    prefetch_mode: ~

  val:
    name: REDS4
    type: VideoRecurrentTestDataset
    dataroot_gt: ../../data/REDS4/train_sharp
    dataroot_lq: ../../data/REDS4/train_sharp_bicubic/X4
    cache_data: true
    io_backend:
      type: disk

    num_frame: -1  # not needed
    # padding: reflection_circle

# network structures
network_g:
  type: BasicAttention_VSR
  num_feat: 64
  num_block: 20
  image_ch: 3
  num_frame: 15
  num_extract_block: 18
  depth: 2
  heads: 1
  patch_size: 8
  spynet_path: experiments/pretrained_models/flowNet/spynet_sintel_final-3d2a1287.pth
  # spynet_path: experiments/pretrained_models/flownet/pwcnet.pytorch

# path
path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~

# training settings
train:
  ema_decay: 0.999
  optim_g:
    type: Adam
    lr: !!float 2e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: CosineAnnealingRestartLR
    periods: [600000]
    restart_weights: [1]
    eta_min: !!float 1e-7

  total_iter: 600000
  warmup_iter: -1  # no warm up
  fix_flow: 10000
  flow_lr_mul: 0.125

  # losses
  pixel_opt:
    type: CharbonnierLoss
    loss_weight: 1.0
    reduction: mean

# validation settings
val:
  val_freq: !!float 5e4
  save_img: false

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 0
      test_y_channel: false
    ssim:
      type: calculate_ssim
      crop_border: 0
      test_y_channel: false

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e4
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500

find_unused_parameters: true
